---
-   hosts: all
    sudo: yes
    gather_facts:no
    vars:
        noc_ntpserver: 1.be.pool.ntp.org
    
    tasks:
    
    - name: install ntp
      apt: name=ntp state=installed update_cache=yes
        
    - name:
      template: src=/vagrant/files/ntp.conf dest=/etc/ntp.conf owner=root group=root
      notify: restart ntp
      
    - name: start ntp
      service: name=ntp state=started
      
    handlers:
    
    - name: restart ntp
      service: name=ntp state=restarted
