---
-   hosts: all
    sudo: yes
    gather_facts: no
  
    tasks:
  
    - name: install ntp
      apt: name=ntp state=installed update_cache=yes
      
    - name: write our ntp.conf
      copy: src=/vagrant/files/ntp.conf dest=/etc/ntp.conf mode=644 owner=root group=root
      #Notifies sturen opdrachten naar de helpers, als de task is uitgevoerd gaat hij naar de handler met overeenkomende naam en voert dit uit
      notify: restart ntp
    
    #Gemaakt voor de zekerheid normaal zou het up moeten zijn maar als het niet zo is word hij toch nog gestart
    - name: start ntp
      service: name=ntp state=started
      
    handlers:
    
    - name: restart ntp
      service: name=ntp state=restarted
  